# 애플리케이션(프로젝트) 이름을 지정하는 설정
# 로그에 표시 됨.
spring.application.name=timelog

# ------------------------------------
# 1. 서버 포트 설정
# ------------------------------------
server.port=8800



# ------------------------------------
# 2. MySQL 데이터베이스 연결 설정
# ------------------------------------	
spring.datasource.url=jdbc:mysql://localhost:3306/time_log_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=time_log_user
spring.datasource.password=1234


# ------------------------------------
# 3. Spring Data JPA 설정
# ------------------------------------

# show-sql 설정 - true로 설정하면 실행되는 SQL 쿼리를 콘솔에 출력
spring.jpa.show-sql=true

# ddl-auto 설정 - update: 애플리케이션 실행 시 데이터베이스 스키마를 자동으로 업데이트
spring.jpa.hibernate.ddl-auto=update

# format_sql 설정 - true로 설정하면 출력되는 SQL 쿼리를 보기 좋게 포맷팅하여 콘솔에 출력
spring.jpa.properties.hibernate.format_sql=true

# 방언 설정 (MySQL 8 기준)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# ------------------------------------
# 4. Thymeleaf 설정
# ------------------------------------

# 템플릿 경로 변경 옵션
# 기본 설정이 templates로 아래 옵션을 거의 쓰지 않음
# spring.thymeleaf.prefix=classpath:/templates/

# 확장자 변경 옵션으로 아래 옵션도 기본 설정으로 쓰지 않음
# spring.thymeleaf.suffix=.html

# 스프링 부트 2.x 이상 및 Thymeleaf 3.x부터는 기본값이 이미 HTML이여서 아래 옵션도 쓰지 않아도 됨.
# spring.thymeleaf.mode=HTML5

# 아래 옵션도 기본값이 UTF-8이라 안 건드려도 됨.
# spring.thymeleaf.encoding=UTF-8

# ***(개발 환경에서 필수)***
# 캐시 끄기 -> HTML 수정할 때마다 서버 재시작했을 때 반영이 안되는 것을 막아줌.
# 즉 false로 설정하면 HTML 수정하면 바로 반영 됨.
spring.thymeleaf.cache=false

# ------------------------------------
# 5. Spring Security 인증 설정
# ------------------------------------
spring.security.user.name=admin
spring.security.user.password=1234